### ISSUE TITLE
stereo-seq怎么对接Velocity

### ISSUE THREAD

**Issue by liyu-ynu** [BGIResearch/Stereo-seq#1]

**Comment by liyu-ynu** [comment]
你好，请问一下，我用SAW标准流程02.count这一步得到的bam文件，用Velocity run准备把bam转换为loom，出现了以下错误，想问一下是什么原因？感谢您解答，谢谢。
Traceback (most recent call last):
  File "/public/home/liyu/miniconda3/envs/r4.2/bin/velocyto", line 11, in <module>
    sys.exit(cli())
  File "/public/home/liyu/miniconda3/envs/r4.2/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/public/home/liyu/miniconda3/envs/r4.2/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/public/home/liyu/miniconda3/envs/r4.2/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/public/home/liyu/miniconda3/envs/r4.2/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/public/home/liyu/miniconda3/envs/r4.2/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/public/home/liyu/miniconda3/envs/r4.2/lib/python3.10/site-packages/velocyto/commands/run.py", line 113, in run
    return _run(bamfile=bamfile, gtffile=gtffile, bcfile=bcfile, outputfolder=outputfolder,
  File "/public/home/liyu/miniconda3/envs/r4.2/lib/python3.10/site-packages/velocyto/commands/_run.py", line 159, in _run
    exincounter.peek(bamfile[0])
  File "/public/home/liyu/miniconda3/envs/r4.2/lib/python3.10/site-packages/velocyto/counter.py", line 158, in peek
    raise IOError("The bam file does not contain cell and umi barcodes appropriatelly formatted. If you are runnin UMI-less data you should use the -U flag.")
OSError: The bam file does not contain cell and umi barcodes appropriatelly formatted. If you are runnin UMI-less data you should use the -U flag.
